import{a as w,i as y,S as L}from"./assets/vendor-tnUJPedx.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&o(u)}).observe(document,{childList:!0,subtree:!0});function a(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(r){if(r.ep)return;r.ep=!0;const n=a(r);fetch(r.href,n)}})();const b="48291953-85546cde0c7bc9cda0531770b",S="https://pixabay.com/api/",q=20;let d=1;async function g(t,e=1){try{const a=`${S}?key=${b}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${q}&page=${e}`,o=await w.get(a);if(o.data.hits.length===0)throw new Error("No images found");return d=e,o.data}catch(a){throw a}}function P(){d=1}function E(){return d}function f(){const t=document.querySelector(".gallery");t.innerHTML=""}function p(t){const e=document.querySelector(".gallery"),a=t.map(o=>`
      <a href="${o.largeImageURL}" class="gallery-item">
        <img src="${o.webformatURL}" alt="${o.tags}" class="gallery-image" />
        <div class="image-info">
          <p>Likes: <span>${o.likes}</span></p>
          <p>Views: <span>${o.views}</span></p>
          <p>Comments: <span>${o.comments}</span></p>
          <p>Downloads: <span>${o.downloads}</span></p>
        </div>
      </a>
    `).join("");e.insertAdjacentHTML("beforeend",a)}function i(){y.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}function h(){const t=document.querySelector(".loading");t.style.display="block";const e=document.querySelector(".load-more");e.style.marginBottom="20px"}function l(){const t=document.querySelector(".loading");t.style.display="none"}function s(t){const e=document.querySelector(".load-more");e.style.display=t?"block":"none"}function $(){y.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}s(!1);let c="",m=new L(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,showCounter:!1});document.querySelector(".search-form").addEventListener("submit",async function(t){if(t.preventDefault(),c=document.querySelector(".search-input").value.trim(),!c){s(!1),f(),i();return}P(),f(),s(!1),h();try{const e=await g(c,1);if(l(),e.hits.length===0){s(!1),i();return}p(e.hits),m.refresh(),s(e.totalHits>e.hits.length)}catch(e){l(),s(!1),i(),console.error(e)}});document.querySelector(".load-more").addEventListener("click",async function(){const t=E()+1;h();try{const e=await g(c,t);if(l(),e.hits.length===0){s(!1);return}p(e.hits),m.refresh(),t*15>=e.totalHits?(s(!1),$()):s(!0);const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}catch(e){l(),s(!1),i(),console.error(e)}});
//# sourceMappingURL=index.js.map
